apiVersion: v1
kind: Service
metadata:
  name: gcp-visualizer-backend
  namespace: gcp-visualizer
  labels:
    app: gcp-visualizer-backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: gcp-visualizer-backend

---
apiVersion: v1
kind: Service
metadata:
  name: gcp-visualizer-frontend
  namespace: gcp-visualizer
  labels:
    app: gcp-visualizer-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: gcp-visualizer-frontend

